# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: boletin-drf_restframwork_postgres
    container_name: boletin-drf_djangorest_postgres
    env_file:
      - .envs/.local/.postgres
    volumes:
      - boletindrf_restf_data:/var/lib/postgresql/data
      # - djangobasepro_data_backups:/backups
    ports:
      - 5432:5432

volumes:
  boletindrf_restf_data:
  # djangobasepro_data_backups:
